- backend/src/app.py
- backend/src/repositories/db_service.py
- backend/src/repositories/email_manager.py
- backend/src/repositories/exam.py
- backend/src/repositories/monitor.py
- backend/src/repositories/patient.py
- backend/src/repositories/permission_manager.py
- backend/src/repositories/report_manager.py
- backend/src/repositories/results.py
- backend/src/repositories/session_manager.py
- backend/src/repositories/user.py
- backend/src/repositories/workers.py
- backend/src/system.py
>  translare Class diagram into real classes  

- database/README.md
- database/schema.sql
- database/seed.sql
- database/test.sql
> finishing "create schema.sql seed.sql"

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/LogIn.js
- frontend/src/Main.js
- frontend/src/SignIn.js
- run.sh
> basic main, Signin, login, register pages

- frontend/src/AccManage.js
- frontend/src/AdminMain.js
- frontend/src/App.js
- frontend/src/LogIn.js
- frontend/src/PatientMain.js
- frontend/src/Register.js
- frontend/src/RoleContext.js
> added Role-Based Access Control instead of tokens

- frontend/src/Exam.js
> Started front end for exams. 

- backend/src/repositories/monitor.py
Reverts IndecentTulip/Online-Health-Monitoring-System#116
> Revert "updated smart monitor"

- database/schema.sql
Reverts IndecentTulip/Online-Health-Monitoring-System#118
> Revert "revers"

- backend/src/app.py
- backend/src/system.py
- frontend/src/Components/Profile/Profile.js
- frontend/src/Components/Results/InsertTestResults.js
- frontend/src/Components/Results/TestResultsDoctor.js
- frontend/src/Components/Results/TestResultsPatient.js
> 70% of Staff is implemented

- backend/src/app.py
- backend/src/system.py
- frontend/src/Components/Exam/PrescExam.js
- frontend/src/Components/Monitor/Monitor.js
> ~70% of the Doctor is made

- backend/src/app.py
- backend/src/repositories/patient.py
- backend/src/repositories/user.py
- backend/src/system.py
- frontend/src/Components/Auth/LogIn.js
> added check if account is aproved or not

- backend/src/app.py
- backend/src/repositories/patient.py
- backend/src/system.py
> Aproval of Patient Accounts is Implemented TXH for help Blade

- backend/src/app.py
- backend/src/repositories/exam.py
- backend/src/repositories/patient.py
- backend/src/repositories/workers.py
- backend/src/system.py
- database/schema.sql
- database/seed.sql
- frontend/src/Components/Exam/PrescExam.js
> Exam Assigment is implemented TXH Jason

- backend/src/app.py
- backend/src/repositories/exam.py
- backend/src/repositories/results.py
- backend/src/system.py
- frontend/src/Components/Results/InsertTestResults.js
> Implemented API and backend for Result assigment

- backend/src/app.py
- backend/src/repositories/exam.py
- backend/src/system.py
- frontend/src/Components/Results/InsertTestResults.js
> changed Result assigmet, now test types are separate

- backend/src/app.py
- backend/src/repositories/results.py
- backend/src/system.py
- database/schema.sql
- frontend/src/Components/Results/DelTestResults.js
- frontend/src/index.css
> Test results deletetion for Admin is implemented API and backend logic

- backend/src/app.py
- backend/src/repositories/patient.py
- backend/src/repositories/results.py
- backend/src/repositories/user.py
- backend/src/repositories/workers.py
- backend/src/system.py
- database/schema.sql
- frontend/src/Components/Accounts/ManageAcc.js
- frontend/src/Components/Auth/LogIn.js
- frontend/src/Components/Auth/Register.js
> Implemented Account menagment for Admin, removed password hashing for now

- backend/src/repositories/report_manager.py
> syntax fixes and you can send emails now

- backend/src/repositories/monitor.py
- backend/src/repositories/results.py
Implementation for result searches and monitors
> monitor and result search

- backend/src/app.py
- backend/src/repositories/email_manager.py
- backend/src/repositories/monitor.py
- backend/src/repositories/report_manager.py
- backend/src/system.py
- frontend/src/Components/Doctor/DoctorMain.js
- frontend/src/Components/Monitor/Monitor.js
- frontend/src/Components/Reports/DocPredict.js
Can't find where she specified doctors should view all patients reports, so allowing it for now. My code for that works put the other doesn't.
Will start Implementing searching for results tomorrow.
> Reports Done, Monitors Done, Doctor Viewing Reports sort of works.

- frontend/src/Components/Exam/PrescExam.css
Resubmitting since I am not getting any notification of the CSS being committed
> CSS for PrescExams

- backend/src/app.py
- backend/src/repositories/results.py
- backend/src/system.py
- frontend/src/Components/Results/TestResultsDoctor.js
Patient search should be easy to add later
> Implement result search for doctor

- frontend/src/Components/Monitor/Monitor.css
- frontend/src/Components/Results/DelTestResults.css
- frontend/src/Components/Results/DelTestResults.js
- frontend/src/Components/Results/InsertTestResults.css
- frontend/src/Components/Results/InsertTestResults.js
- frontend/src/Components/Results/TestResultsDoctor.css
- frontend/src/Components/Results/TestResultsDoctor.js
Please Let me know if there needs to be any changes.
> CSS for DelTestResults DONE , CSS for InsertTestResults DONE, CSS for TestResulsPatient DONE, and update of CSS TestResultsDoctor

- backend/src/app.py
- backend/src/repositories/report_manager.py
- backend/src/system.py
- frontend/src/Components/Profile/Profile.js
- frontend/src/Components/Reports/Prediction.js
> fix date issue with prediction reports

- backend/src/app.py
- backend/src/repositories/report_manager.py
- backend/src/system.py
- frontend/src/Components/Profile/Profile.js
- frontend/src/Components/Reports/Prediction.js
Reverts IndecentTulip/Online-Health-Monitoring-System#188
> Revert "fix date issue with prediction reports"

- backend/src/app.py
- backend/src/repositories/report_manager.py
- database/schema.sql
- frontend/package-lock.json
- frontend/src/Components/Reports/Prediction.js
- frontend/src/Components/Results/TestResultsDoctor.js
- frontend/src/Components/Results/TestResultsPatient.js
> drop down for serach and deletion of doctors via making FK nullable

- frontend/src/Components/Profile/MainContence.css
- frontend/src/Components/Profile/MainContence.js
- frontend/src/Main.css
- frontend/src/Main.js
> CSS for Main page and MainContence
